#
# App.yaml for the Netskrafl application on Google App Engine
#
application: netskrafl
version: firefix
runtime: python27
api_version: 1
threadsafe: true

instance_class: B2
manual_scaling:
  instances: 3

# Running on frontend instances of class 2 (256 MB RAM)
#instance_class: F2
#automatic_scaling:
#  min_idle_instances: 4
#  max_idle_instances: 6
#  min_pending_latency: 2000ms
#  max_pending_latency: 5000ms

#inbound_services:
#- warmup
#- channel_presence

builtins:
- deferred: on

handlers:

# Predefined App Engine task queue deferral URL, admin only
- url: /_ah/start
  script: netskrafl.app

# Predefined App Engine task queue deferral URL, admin only
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

# Robots.txt URL, cacheable
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: "1d 0h"

# Favorite icon URL, cacheable
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: "1d 0h"

# Internet Explorer & Windows 8 resource file, can be cached  
- url: /browserconfig.xml
  static_files: static/browserconfig.xml
  upload: static/browserconfig.xml
  expiration: "1d 0h"

# Special Apple iOS URLs for image resources, all cacheable
- url: /apple-touch-icon.png
  static_files: static/touch-icon-ipad-retina.png
  upload: static/touch-icon-ipad-retina.png
  expiration: "1d 0h"
- url: /touch-icon-ipad.png
  static_files: static/touch-icon-ipad.png
  upload: static/touch-icon-ipad.png
  expiration: "1d 0h"
- url: /touch-icon-ipad-retina.png
  static_files: static/touch-icon-ipad-retina.png
  upload: static/touch-icon-ipad-retina.png
  expiration: "1d 0h"
- url: /touch-icon-iphone-retina.png
  static_files: static/touch-icon-iphone-retina.png
  upload: static/touch-icon-iphone-retina.png
  expiration: "1d 0h"

# Image files that can be cached
- url: /static/(.*\.(gif|png|jpg))(\?.*)?$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$
  expiration: "1d 0h"

# CSS files that can be cached
- url: /static/(.*\.css)(\?.*)?$
  static_files: static/\1
  upload: static/.*\.css$
  mime_type: text/css
  expiration: "0d 1h" # Was "1d 0h"

# Catchall for JavaScript
- url: /static/(.*\.min\.js)(\?.*)?$
  static_files: static/\1
  upload: static/.*\.min\.js$
  mime_type: application/javascript
  expiration: "0d 1h" # Was "1d 0h"

# Font files that can be cached
- url: /static/glyphicons-regular.ttf
  static_files: static/glyphicons-regular.ttf
  upload: static/glyphicons-regular.ttf
  expiration: "1d 0h"
  mime_type: application/font-sfnt
- url: /static/glyphicons-regular.eot
  static_files: static/glyphicons-regular.eot
  upload: static/glyphicons-regular.eot
  expiration: "1d 0h"
  mime_type: application/vnd.ms-fontobject
- url: /static/glyphicons-regular.svg
  static_files: static/glyphicons-regular.svg
  upload: static/glyphicons-regular.svg
  expiration: "1d 0h"
  mime_type: image/svg+xml
- url: /static/glyphicons-regular.woff
  static_files: static/glyphicons-regular.woff
  upload: static/glyphicons-regular.woff
  expiration: "1d 0h"
  mime_type: application/font-woff

# MP3 sound files that can be cached  
- url: /static/(.*\.mp3)$
  static_files: static/\1
  upload: static/.*\.mp3$
  mime_type: audio/mpeg
  expiration: "1d 0h"

# Admin web URLs, requiring admin authorization
- url: /admin/.*
  script: admin.app
  login: admin
  auth_fail_action: unauthorized

# Catchall for all other URLS
- url: .*
  script: netskrafl.app

# Files that should not be uploaded to App Engine
skip_files:
- ^resources/.*\.txt$   # Raw text resources, such as word lists
- ^resources/.*\.text\.dawg$   # DAWG trees in text form
- ^resources/.*\.dawg\.pickle$ # DAWG trees in pickled form
- ^(.*/)?.*\.psd$       # Photoshop files
- ^(.*/)?.*\.ai$        # Illustrator files
- ^(.*/)?.*\.log$       # Local log files
- ^(.*/)?.*\.md$        # MarkDown documentation files
- ^(.*/)?.*\.bat$       # Windows batch files
- ^(.*/)?.*\.bak$       # Backup files
- ^(.*/)?.*\.tmp$       # Temporary files
- ^(.*/)?.*\.TMP$       # Temporary files
- ^(.*/)?.*\.less$      # Style sheets in LESS, to be compiled to CSS
- ^(.*/)?#.*#$          # File names enclosed in hashes
- ^(.*/)?.*~$           # Temporary files ending in a curl
- ^(.*/)?.*\.py[co]$    # Python bytecode files
- ^(.*/)?.*/RCS/.*$
- ^\.git/.*$            # GitHub stuff
- ^node_modules/.*$     # NodeJS stuff, mostly related to Grunt
- ^[gG]runtfile.js$     # Gruntfile
- ^(.*/)?\..*$          # Files whose names start with a period
